export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Anakin Skywalker",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Bizarro",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Unknown Master",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Guillaume Hawks",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Sponger",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpg",
    username: "Ironman",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpg",
    username: "Son Goku",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpg",
    username: "Light Yagami",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpg",
    username: "Spiderman",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpg",
    username: "Red Hood",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Best Movie ever",
    photo: "assets/publication/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/publication/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "My favorite movie",
    photo: "assets/publication/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/publication/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/publication/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/publication/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Best serie ever",
    photo: "assets/publication/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/publication/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Who wanna do a Uno??",
    photo: "assets/publication/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/publication/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
